### ISSUE TITLE
Error in MatchRequest with GeometriesGeoJson

### ISSUE THREAD

**Issue by amehta1128** [gojuno/go.osrm#11]
Hello,

I am trying to execute a MatchRequest using the following parameters:

> Profile: "car",
> Coordinates: osrm.NewGeometryFromPointSet(*points),
> Timestamps:  timestamps,
> Radiuses:	 accuracy,
> Annotations: osrm.AnnotationsNodes,
> Overview:    osrm.OverviewFull,
> Geometries:  osrm.GeometriesGeojson,

This results in the following error:

> json: cannot unmarshal object into Go struct field Matching.geometry of type geo.PointSet

When I try with osrm.GeometriesPolyline6, the request works fine. For now I only care about the Matching.Geometry part of the response, but I am wondering what information I may be losing by making this switch. 

Thanks

**Comment by sbinq** [comment]
Hi @amehta1128, thanks for reporting the issue!

I don't think any information is lost when using "polyline6" vs "geojson" (according to OSRM docs it would be smth like `{"type": "LineString", "coordinates": [[120.0, 10.0], [120.1, 10.0], [120.2, 10.0], [120.3, 10.0]]}` instead of polyline, i.e. points only, no extra info).

But this definitely needs to be fixed (I think we'll be able to do it soon).

**Comment by sbinq** [comment]
Should be fixed now
